networks:
  listings_net:

services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: listings_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - listings_net

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/listings_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - listings_net

volumes:
  postgres_data: