name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d

      - name: Run tests
        run: docker compose run --rm api pytest

      - name: Shut down services
        if: always()
        run: docker compose down --remove-orphans 